// ============================================================================
// tb_multiply_manager_wide.sv
//
// Self-checking testbench for the WIDE (JOINED) thread of multiply_manager.
// Expected iteration counts are read from wide_expected.csv, generated by
// wide_reference.py (independent software reference, no RTL-mimicking).
//
// CSV format (one header line then data):
//   index,name,expected_count
//
// The test vectors in initial begin must match the order in wide_reference.py.
// ============================================================================

`timescale 1ns/1ps

module tb_multiply_manager_wide;

    // ----- Parameters (match DUT) -----
    localparam int NARROW_WIDTH           = 18;
    localparam int INTEGER_BITS           = 2;
    localparam int ITERATION_COUNT_WIDTH  = 16;
    localparam int LOW                    = 0;

    // Wide-mode geometry
    localparam int WIDE_HIGH_W  = 18;
    localparam int WIDE_LOW_W   = 17;
    localparam int WIDE_REG_W   = 36;
    localparam int WIDE_FRAC    = 33;

    // ----- DUT I/O -----
    logic clk, rst, kill, received;
    logic start_left, start_right, start_wide;
    logic julia_type;
    logic [3:0] magnitude_negation_encoding;
    logic [4:0] max_iteration;
    logic signed [NARROW_WIDTH-1:0] julia_c_x, julia_c_y;
    logic signed [NARROW_WIDTH-1:0] starting_x_reg_1, starting_x_reg_2;
    logic signed [NARROW_WIDTH-1:0] starting_y_reg_1, starting_y_reg_2;

    logic done, done_side;
    logic [ITERATION_COUNT_WIDTH-1:0] iteration_out;

    // ----- DUT -----
    multiply_manager #(
        .NARROW_WIDTH(NARROW_WIDTH),
        .INTEGER_BITS(INTEGER_BITS),
        .ITERATION_COUNT_WIDTH(ITERATION_COUNT_WIDTH),
        .LOWEST_MAX_ITERATION_POWER(LOW)
    ) dut (
        .clk(clk), .rst(rst), .kill(kill), .received(received),
        .start_left(start_left), .start_right(start_right), .start_wide(start_wide),
        .julia_type(julia_type),
        .magnitude_negation_encoding(magnitude_negation_encoding),
        .max_iteration(max_iteration),
        .julia_c_x(julia_c_x), .julia_c_y(julia_c_y),
        .starting_x_reg_1(starting_x_reg_1), .starting_x_reg_2(starting_x_reg_2),
        .starting_y_reg_1(starting_y_reg_1), .starting_y_reg_2(starting_y_reg_2),
        .done(done), .done_side(done_side), .iteration_out(iteration_out)
    );

    // ----- Clock -----
    initial clk = 0;
    always #5 clk = ~clk;

    // ----- Bookkeeping -----
    int unsigned errors = 0;
    int unsigned checks = 0;

    // ========================================================================
    // Expected counts loaded from CSV
    // ========================================================================

    localparam int MAX_TESTS = 256;
    int unsigned expected_count [MAX_TESTS];
    int          n_tests = 0;

    // Load expected counts from hex file (one value per line, generated by wide_reference.py)
    initial begin
        $readmemh("wide_expected.hex", expected_count);
        $display("Loaded expected counts from wide_expected.hex  [0]=%0d [1]=%0d",
                 expected_count[0], expected_count[1]);
    end

    // ========================================================================
    // Format helpers
    // ========================================================================

    function automatic logic [WIDE_REG_W-1:0] to_wide(input real v);
        longint signed   raw;
        logic signed [WIDE_HIGH_W-1:0] hi;
        logic        [WIDE_LOW_W-1:0]  lo;
        logic        [WIDE_REG_W-1:0]  result;
        raw = longint'($rtoi(v * real'(1 << WIDE_FRAC)));
        hi  = WIDE_HIGH_W'(raw >>> WIDE_LOW_W);
        lo  = WIDE_LOW_W'(raw - (longint'(hi) <<< WIDE_LOW_W));
        result = {hi, 1'b0, lo};
        return result;
    endfunction

    function automatic logic signed [NARROW_WIDTH-1:0] to_narrow(input real v);
        return $signed(int'($rtoi(v * real'(1 << (NARROW_WIDTH - INTEGER_BITS)))));
    endfunction

    // ========================================================================
    // Helpers
    // ========================================================================

    task automatic do_reset();
        rst = 1; kill = 0; received = 0;
        start_left = 0; start_right = 0; start_wide = 0;
        julia_type = 0; magnitude_negation_encoding = 4'b0000;
        max_iteration = 0;
        julia_c_x = 0; julia_c_y = 0;
        starting_x_reg_1 = 0; starting_x_reg_2 = 0;
        starting_y_reg_1 = 0; starting_y_reg_2 = 0;
        repeat (3) @(posedge clk);
        rst = 0;
        @(posedge clk);
    endtask

    function automatic void check(input logic cond, input string msg);
        checks++;
        if (!cond) begin
            errors++;
            $display("  [FAIL] %s   (t=%0t)", msg, $time);
        end
    endfunction

    task automatic drive_wide_inputs(
            input logic                           jtype,
            input logic [3:0]                     enc,
            input logic [4:0]                     maxit,
            input logic signed [NARROW_WIDTH-1:0] jcx,
            input logic signed [NARROW_WIDTH-1:0] jcy,
            input logic [WIDE_REG_W-1:0]          px_wide,
            input logic [WIDE_REG_W-1:0]          py_wide);
        julia_type                   = jtype;
        magnitude_negation_encoding  = enc;
        max_iteration                = maxit;
        julia_c_x                    = jcx;
        julia_c_y                    = jcy;
        starting_x_reg_1 = $signed(px_wide[WIDE_REG_W-1 : WIDE_REG_W-NARROW_WIDTH]);
        starting_x_reg_2 = NARROW_WIDTH'({1'b0, px_wide[WIDE_LOW_W-1:0]});
        starting_y_reg_1 = $signed(py_wide[WIDE_REG_W-1 : WIDE_REG_W-NARROW_WIDTH]);
        starting_y_reg_2 = NARROW_WIDTH'({1'b0, py_wide[WIDE_LOW_W-1:0]});
    endtask

    // ========================================================================
    // Core run task — compares against pre-loaded expected_count[test_idx]
    // ========================================================================

    task automatic run_wide(
            input string                          name,
            input int                             test_idx,
            input logic                           jtype,
            input logic [3:0]                     enc,
            input logic [4:0]                     maxit,
            input logic signed [NARROW_WIDTH-1:0] jcx,
            input logic signed [NARROW_WIDTH-1:0] jcy,
            input logic [WIDE_REG_W-1:0]          px_wide,
            input logic [WIDE_REG_W-1:0]          py_wide,
            input int unsigned                    timeout_cycles = 500000);

        int unsigned exp;
        int unsigned cyc;
        logic captured;

        exp = expected_count[test_idx];

        drive_wide_inputs(jtype, enc, maxit, jcx, jcy, px_wide, py_wide);

        @(negedge clk); start_wide = 1;
        @(negedge clk); start_wide = 0;

        cyc = 0; captured = 0;
        while (!captured) begin
            @(posedge clk);
            cyc++;
            if (done) begin
                // Wait one cycle for iteration_out to settle after done asserts
                @(posedge clk);
                check(done_side == 1'b0,
                      {name, ": done_side should be 0 (wide uses left thread)"});
                check(done == 1'b1, {name, ": done dropped on settle cycle"});
                check(iteration_out == exp[ITERATION_COUNT_WIDTH-1:0],
                      $sformatf("%s: count mismatch  dut=%0d  ref=%0d",
                                name, iteration_out, exp));
                // repeat (3) begin
                //     @(posedge clk);
                //     check(done == 1'b1, {name, ": done dropped before received"});
                //     check(iteration_out == exp[ITERATION_COUNT_WIDTH-1:0],
                //           {name, ": iteration_out changed while holding"});
                // end
                captured = 1;
            end
            if (cyc > timeout_cycles) begin
                check(1'b0, {name, ": TIMEOUT waiting for done"});
                captured = 1;
            end
        end

        @(negedge clk); received = 1;
        @(negedge clk); received = 0;
        @(posedge clk);
        check(done == 1'b0, {name, ": done did not drop after received"});

            // $display("  [ OK ] %-50s  dut=%0d  ref=%0d  (%0d cycles)",
            //         name, iteration_out, exp, cyc);
    endtask



    // ========================================================================
    // Test sequence
    // ========================================================================

    initial begin
        int idx;  // tracks position in expected_count[]

        $dumpfile("sim/waves/tb_multiply_manager_wide.vcd");
        $dumpvars(0, tb_multiply_manager_wide);

        $display("==== tb_multiply_manager_wide : wide (JOINED) thread ====");
        do_reset();
        check(done == 1'b0, "after reset: done should be low");

        idx = 0;

        // 1. Origin
        run_wide("mandel c=(0,0) max=8", idx,
                 1'b0, 4'b0000, 5'd3, '0, '0,
                 to_wide(0.0), to_wide(0.0));
        idx++;

        // // 2. Exterior escapes
        // run_wide("mandel c=(1.8,0) escape", idx,
        //          1'b0, 4'b0000, 5'd6, '0, '0,
        //          to_wide(1.8), to_wide(0.0));
        // idx++;
        // run_wide("mandel c=(-1.9,0) escape", idx,
        //          1'b0, 4'b0000, 5'd6, '0, '0,
        //          to_wide(-1.9), to_wide(0.0));
        // idx++;
        // run_wide("mandel c=(0,1.8) escape", idx,
        //          1'b0, 4'b0000, 5'd6, '0, '0,
        //          to_wide(0.0), to_wide(1.8));
        // idx++;

        // // 3. Interior
        // run_wide("mandel c=(-1,0) interior max=16", idx,
        //          1'b0, 4'b0000, 5'd4, '0, '0,
        //          to_wide(-1.0), to_wide(0.0));
        // idx++;
        // run_wide("mandel c=(-0.5,0) interior max=16", idx,
        //          1'b0, 4'b0000, 5'd4, '0, '0,
        //          to_wide(-0.5), to_wide(0.0));
        // idx++;

        // // 4. Boundary
        // run_wide("mandel c=(0.3,0.5)", idx,
        //          1'b0, 4'b0000, 5'd6, '0, '0,
        //          to_wide(0.3), to_wide(0.5));
        // idx++;
        // run_wide("mandel c=(-0.7,0.3)", idx,
        //          1'b0, 4'b0000, 5'd6, '0, '0,
        //          to_wide(-0.7), to_wide(0.3));
        // idx++;
        // run_wide("mandel c=(-0.745,0.1)", idx,
        //          1'b0, 4'b0000, 5'd7, '0, '0,
        //          to_wide(-0.745), to_wide(0.1));
        // idx++;

        // // 5. Deep zoom
        // run_wide("seahorse valley (-0.7436,0.1319) max=128", idx,
        //          1'b0, 4'b0000, 5'd7, '0, '0,
        //          to_wide(-0.7436), to_wide(0.1319));
        // idx++;
        // run_wide("seahorse valley (-0.74364,0.13182) max=128", idx,
        //          1'b0, 4'b0000, 5'd7, '0, '0,
        //          to_wide(-0.74364), to_wide(0.13182));
        // idx++;
        // run_wide("test (2.0, 2.0) max=512", idx,
        //          1'b0, 4'b0000, 5'd9, '0, '0,
        //          to_wide(2.0), to_wide(2.0));
        // idx++;

        // // Fractional clusters — inlined (no ref port needed)
        // // fp A (-0.75, 0.10)
        // run_wide("fp A (-0.75, 0.10) base", idx, 1'b0, 4'b0000, 5'd10, '0, '0, to_wide(-0.75),                to_wide(0.10));               idx++;
        // run_wide("fp A (-0.75, 0.10) +dx",  idx, 1'b0, 4'b0000, 5'd10, '0, '0, to_wide(-0.75+1.0/(1<<20)),   to_wide(0.10));               idx++;
        // run_wide("fp A (-0.75, 0.10) -dx",  idx, 1'b0, 4'b0000, 5'd10, '0, '0, to_wide(-0.75-1.0/(1<<20)),   to_wide(0.10));               idx++;
        // run_wide("fp A (-0.75, 0.10) +dy",  idx, 1'b0, 4'b0000, 5'd10, '0, '0, to_wide(-0.75),                to_wide(0.10+1.0/(1<<26)));   idx++;
        // run_wide("fp A (-0.75, 0.10) -dy",  idx, 1'b0, 4'b0000, 5'd10, '0, '0, to_wide(-0.75),                to_wide(0.10-1.0/(1<<26)));   idx++;
        // // fp B (-0.7436, 0.1319)
        // run_wide("fp B (-0.7436, 0.1319) base", idx, 1'b0, 4'b0000, 5'd10, '0, '0, to_wide(-0.7436),               to_wide(0.1319));              idx++;
        // run_wide("fp B (-0.7436, 0.1319) +dx",  idx, 1'b0, 4'b0000, 5'd10, '0, '0, to_wide(-0.7436+1.0/(1<<22)),  to_wide(0.1319));              idx++;
        // run_wide("fp B (-0.7436, 0.1319) -dx",  idx, 1'b0, 4'b0000, 5'd10, '0, '0, to_wide(-0.7436-1.0/(1<<22)),  to_wide(0.1319));              idx++;
        // run_wide("fp B (-0.7436, 0.1319) +dy",  idx, 1'b0, 4'b0000, 5'd10, '0, '0, to_wide(-0.7436),               to_wide(0.1319+1.0/(1<<28))); idx++;
        // run_wide("fp B (-0.7436, 0.1319) -dy",  idx, 1'b0, 4'b0000, 5'd10, '0, '0, to_wide(-0.7436),               to_wide(0.1319-1.0/(1<<28))); idx++;
        // // fp C seahorse zoom
        // run_wide("fp C seahorse zoom base", idx, 1'b0, 4'b0000, 5'd10, '0, '0, to_wide(-0.74364),               to_wide(0.13182));              idx++;
        // run_wide("fp C seahorse zoom +dx",  idx, 1'b0, 4'b0000, 5'd10, '0, '0, to_wide(-0.74364+1.0/(1<<24)),  to_wide(0.13182));              idx++;
        // run_wide("fp C seahorse zoom -dx",  idx, 1'b0, 4'b0000, 5'd10, '0, '0, to_wide(-0.74364-1.0/(1<<24)),  to_wide(0.13182));              idx++;
        // run_wide("fp C seahorse zoom +dy",  idx, 1'b0, 4'b0000, 5'd10, '0, '0, to_wide(-0.74364),               to_wide(0.13182+1.0/(1<<30))); idx++;
        // run_wide("fp C seahorse zoom -dy",  idx, 1'b0, 4'b0000, 5'd10, '0, '0, to_wide(-0.74364),               to_wide(0.13182-1.0/(1<<30))); idx++;

        // // LSB jitter
        // for (int i = 0; i < 8; i++) begin
        //     real eps;
        //     eps = (i - 4) * (1.0 / (1 << 32));
        //     run_wide($sformatf("LSB jitter %0d", i), idx,
        //              1'b0, 4'b0000, 5'd8, '0, '0,
        //              to_wide(-0.75 + eps), to_wide(0.1 - eps));
        //     idx++;
        // end

        // // 6. Julia
        // run_wide("julia c=(-0.8,0.156) z0=(0,0)", idx,
        //          1'b1, 4'b0000, 5'd6,
        //          to_narrow(-0.8), to_narrow(0.156),
        //          to_wide(0.0), to_wide(0.0));
        // idx++;
        // run_wide("julia c=(0.285,0.01) z0=(0.1,0.1)", idx,
        //          1'b1, 4'b0000, 5'd6,
        //          to_narrow(0.285), to_narrow(0.01),
        //          to_wide(0.1), to_wide(0.1));
        // idx++;
        // run_wide("julia c=(-0.4,0.6) z0=(-0.5,0.5)", idx,
        //          1'b1, 4'b0000, 5'd6,
        //          to_narrow(-0.4), to_narrow(0.6),
        //          to_wide(-0.5), to_wide(0.5));
        // idx++;

        // // 7. Variants
        // run_wide("burning ship c=(-1.7,-0.01)", idx,
        //          1'b0, 4'b1100, 5'd6, '0, '0,
        //          to_wide(-1.7), to_wide(-0.01));
        // idx++;
        // run_wide("tricorn c=(-0.5,0.5)", idx,
        //          1'b0, 4'b0001, 5'd6, '0, '0,
        //          to_wide(-0.5), to_wide(0.5));
        // idx++;

        // // 8. Back-to-back
        // run_wide("b2b run A  c=(0,0) max=8", idx,
        //          1'b0, 4'b0000, 5'd3, '0, '0,
        //          to_wide(0.0), to_wide(0.0));
        // idx++;
        // run_wide("b2b run B  c=(1.8,0) escape", idx,
        //          1'b0, 4'b0000, 5'd6, '0, '0,
        //          to_wide(1.8), to_wide(0.0));
        // idx++;

        // // 9. Kill mid-computation (no expected count needed)
        // begin
        //     drive_wide_inputs(1'b0, 4'b0000, 5'd9, '0, '0,
        //                       to_wide(0.0), to_wide(0.0));
        //     @(negedge clk); start_wide = 1; @(negedge clk); start_wide = 0;
        //     repeat (20) @(posedge clk);
        //     check(done == 1'b0, "kill test: unexpected early done");
        //     @(negedge clk); kill = 1; @(negedge clk); kill = 0;
        //     repeat (10) begin
        //         @(posedge clk);
        //         check(done == 1'b0, "kill test: done asserted after kill");
        //     end
        //     $display("  [ OK ] kill mid-computation (wide)");
        // end

        // // 10. RST mid-computation
        // begin
        //     drive_wide_inputs(1'b0, 4'b0000, 5'd9, '0, '0,
        //                       to_wide(0.0), to_wide(0.0));
        //     @(negedge clk); start_wide = 1; @(negedge clk); start_wide = 0;
        //     repeat (10) @(posedge clk);
        //     @(negedge clk); rst = 1; @(negedge clk); rst = 0;
        //     repeat (5) begin
        //         @(posedge clk);
        //         check(done == 1'b0, "rst test: done asserted after rst");
        //     end
        //     $display("  [ OK ] rst mid-computation (wide)");
        // end

        // Summary
        $display("==== DONE: %0d checks, %0d errors ====", checks, errors);
        if (errors == 0) $display("==== ALL TESTS PASSED ====");
        else             $display("==== %0d FAILURE(S) ====", errors);
        $finish;
    end

    // Global watchdog
    initial begin
        #50_000_000;
        $display("==== GLOBAL TIMEOUT ====");
        $finish;
    end

endmodule